discord:
  token: ${DISCORD_BOT_TOKEN} # Set via environment variable GRIND_REVIEW_DISCORD_TOKEN or DISCORD_BOT_TOKEN
  guild_id: ${DISCORD_GUID_ID} # Required for private server-only bot
  review_channel_id: ${DISCORD_CHANNEL_ID}
  commands_timeout: 5s
  interaction_expiry: 15m

database:
  driver: sqlite3
  dsn: grind_review.db?_busy_timeout=5000&_journal_mode=WAL
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_life: 1h
  query_timeout: 3s
  migrations_path: ./internal/database/migrations

scheduler:
  review_time: "08:00"
  review_channel: ${DISCORD_CHANNEL_ID}
  retry_attempts: 3
  retry_delay: 2s
  lookback_period: 24h

metrics:
  enabled: false
  address: ":9090"

log_level: info